In [5]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print( "data =" + str( data ) )
print( "type(data) ="+ str( type(data) ) )

print( "data.ndim    ="+ str( data.ndim ) )
print( "data.shape   ="+ str( data.shape  ) + " n rows x m cols")
print( "data.size    ="+ str( data.size   ) )
print( "data.dtype   ="+ str( data.dtype  ) )
print( "data.nbytes  ="+ str( data.nbytes ) )

data =[[1 2]
 [3 4]
 [5 6]]
type(data) =<class 'numpy.ndarray'>
data.ndim    =2
data.shape   =(3, 2)
data.size    =6
data.dtype   =int64
data.nbytes  =48


In [8]:
np.array([1, 2, 3], dtype=int)


array([1, 2, 3])

In [9]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [10]:
(d1+d2).dtype

dtype('complex128')

In [15]:
d3 =np.array( [-1, 9, 16] , dtype=complex )
print( "note in complex space sqrt(-1) = 0+1j ")
sqrt_d3 =np.sqrt( d3 ) 
sqrt_d3

note in complex space sqrt(-1) = 0+1j 


array([0.+1.j, 3.+0.j, 4.+0.j])

In [17]:
print( f"sqrt_d3.real ={str( sqrt_d3.real )}")
print( f"sqrt_d3.imag ={str( sqrt_d3.imag )}")

sqrt_d3.real =[0. 3. 4.]
sqrt_d3.imag =[1. 0. 0.]


In [21]:
# use np.linspace to fill an array element with uniformly space values in a range
x = np.linspace( -1, 1, 11 ) # create array, x, with 11 values in range [-1,1]
print( f"x ={x}\n" )

y = np.sin( np.pi * x )
y = np.round( y, decimals=4 )
print( f"y = np.sin( np.pi * x ) ={y}\n" )

x =[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]

y = np.sin( np.pi * x ) =[-0.     -0.5878 -0.9511 -0.9511 -0.5878  0.      0.5878  0.9511  0.9511
  0.5878  0.    ]



In [26]:
# d =[ [1,2,3],
#      [4,5,6],
#      [7,8,9] ]
#
d =np.arange( 1, 10).reshape(3,3)    
print( f"d =str{d}\n" )

print( "# sum all elements")
print( f"d.sum() = {str( d.sum() )}\n")

print( "# sum each column of matrix, d" )
print( f"d.sum(axis=0) ={str( d.sum(axis=0) )}\n")

print( "# sum each row of matrix, d" )
print( f"d.sum(axis=1) ={str( d.sum(axis=1) )}\n")




d =str[[1 2 3]
 [4 5 6]
 [7 8 9]]

# sum each column of matrix, d
d.sum(axis=0) =[12 15 18]

# sum each row of matrix, d
d.sum(axis=1) =[ 6 15 24]

